### ISSUE TITLE
Dragging marker for adjustments

### ISSUE THREAD

**Issue by shujaatak** [yusriltakeuchi/polymaker#4]
It would be highly productive if polymaker includes a functionality to let the user to drag markers to fine tune their location.

**Comment by yusriltakeuchi** [comment]
@shujaatak hey bro, i update this package into  v0.0.5 and i add the draggable marker, maybe you can use this.

https://pub.dev/packages/polymaker/versions/0.0.5

**Comment by shujaatak** [comment]
Amazing! Thank you so much for such this awesome work!
