### ISSUE TITLE
address lookup function

### ISSUE THREAD

**Issue by Watlas** [yusriltakeuchi/polymaker#8]
is there the possibility of making a textfield to search for a certain address?

**Comment by yusriltakeuchi** [comment]
> is there the possibility of making a textfield to search for a certain address?

You mean like using place API?

**Comment by Watlas** [comment]
a simple search field to find a particular location more easily.

Example:

![example ](https://user-images.githubusercontent.com/57519850/142734280-41ba8476-c41e-48cf-9029-b663ca219e57.jpg)

**Comment by OkomoJacob** [comment]
> is there the possibility of making a textfield to search for a certain address?

You can create your own `findPlacesAutocpmleteSearch` then call it in a `ListView.seperated` widget to do it.
Remember to use the `Stack` widget since you'll overlay the **predicted place names** texts on top of the map widget.

**Comment by yusriltakeuchi** [comment]
I will think about adding the address lookup in the next version, and even then, if it is really really needed

**Comment by OkomoJacob** [comment]
Ok, thanks.
But what about issue #9 ? I'm really struggling to get playmaker work. I'll even willing to buy you coffee. The time you'll spend will mean a lot to me.
I'm stuck in my Bsc. project to this but I'm really willing to reciprocate sir.
- [x] Thank you

**Comment by yusriltakeuchi** [comment]
> 

just try with the new version if your problem about geolocator.

**Comment by yusriltakeuchi** [comment]
> Ok, thanks. But what about issue #9 ? I'm really struggling to get playmaker work. I'll even willing to buy you coffee. The time you'll spend will mean a lot to me. I'm stuck in my Bsc. project to this but I'm really willing to reciprocate sir.
> 
>     * [x]  Thank you

just try with the new version if your problem about geolocator.
